name: cookmate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  transparent_image: ^2.0.1
  google_fonts: ^6.3.2
  carousel_slider: ^5.1.1
  country_flags: ^4.1.0
  smooth_page_indicator: ^1.2.1
  flutter_riverpod: ^3.0.3
  path: ^1.9.1
  sqflite: ^2.4.2
  image_picker: ^1.2.1
  uuid: ^4.5.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: "assets/launcher_icon/icon.png"
  min_sdk_android: 21



flutter:
  uses-material-design: true
  assets:
    - assets/lottie/

